sharepoint:
  domain: "DOMAIN"
  username: "USERNAME"
  password: "PASSWORD"
  site: "SITE"
  
oracle:
  host: "HOST"
  port: "PORT"
  user: "USER"
  password: "PASSWORD"
  SID: "SID"

workday:
  username: "USERNAME"
  password: "PASSWORD"
  tenent_name: "TENENT"
  hostname: "HOSTNAME"
